import numpy as np
import random
import math
import ast
import json
from typing import Any, Iterable, List, Tuple
from math import gcd, isqrt


def find_pair(n: int) -> Tuple[int, int]:
    """
    Finds positive integers a > b > n, gcd(a,b)=1, such that
        (a^2 + b)(b^2 + a)
    is a perfect square, using the official construction:
        a = (b-1)^2 + 1
    and Pell-type solutions making 2(b^2 - 3b + 4) a square.

    This matches the official solution logic. If your original problem
    truly had (b^2 + b) instead of (b^2 + a), this construction does not apply.
    """
    if n < 1:
        raise ValueError("n must be a positive integer")

    # We need 2(b^2 - 3b + 4) = k^2.
    # Let x = 2b - 3 (odd). Then this becomes x^2 - 2k^2 = -7.
    # Solutions are generated by multiplying by (3 + 2*sqrt(2)):
    #   (x', k') = (3x + 4k, 2x + 3k)
    #
    # Start from a known solution with odd b: (x,k) = (11,8) -> b = (11+3)/2 = 7.
    x, k = 11, 8

    while True:
        b = (x + 3) // 2

        # gcd(a,b)=gcd( (b-1)^2+1, b ) = gcd(2,b), so we want b odd.
        if b > n and (b & 1):
            a = (b - 1) * (b - 1) + 1
            # (Optional sanity) ensure coprime
            if gcd(a, b) == 1:
                return a, b

        # Next Pell step
        x, k = 3 * x + 4 * k, 2 * x + 3 * k


def solution(parameters):
    n = parameters['n']
    a, b = find_pair(n)
    return [a, b]